theme: jekyll-theme-minimal
logo: /resources/images/logo.png
title: Serge Dmitrieff's homepage
description: A page/blog about biophysics, science, and society.i
markdown: kramdown
kramdown:
    math_engine: mathjax
