theme: jekyll-theme-minimal
author:
    name: "Serge Dmitrieff"
logo: /resources/images/logo.png
title: Serge Dmitrieff's homepage
description: A page/blog about biophysics, science, and society...
markdown: kramdown
highlighter: rouge
kramdown:
    syntax_highlighter: rouge
